spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: root
    password: root
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.springframework.data.mongodb.repository.query: DEBUG